apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: simetra
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317

    processors:
      transform:
        metric_statements:
          - context: datapoint
            statements:
              - set(attributes["host_name"], resource.attributes["service.instance.id"])

    exporters:
      prometheusremotewrite:
        endpoint: http://prometheus:9090/api/v1/write
        resource_to_telemetry_conversion:
          enabled: true

      elasticsearch:
        endpoints:
          - http://elasticsearch:9200
        logs_index: simetra-logs
        sending_queue:
          enabled: true
        flush:
          bytes: 1024
          interval: 1s

    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [transform]
          exporters: [prometheusremotewrite]
        logs:
          receivers: [otlp]
          exporters: [elasticsearch]
