apiVersion: v1
kind: ConfigMap
metadata:
  name: simetra-tenantvector
  namespace: simetra
data:
  tenantvector.json: |
    {
      "Tenants": [
        {
          "Id": "npb-trap",
          "Priority": 1,
          "Metrics": [
            { "Ip": "PLACEHOLDER_NPB_IP", "Port": 161, "MetricName": "npb_port_status_P1" },
            { "Ip": "PLACEHOLDER_NPB_IP", "Port": 161, "MetricName": "npb_port_rx_octets_P1" },
            { "Ip": "PLACEHOLDER_NPB_IP", "Port": 161, "MetricName": "npb_port_tx_octets_P1" },
            { "Ip": "PLACEHOLDER_NPB_IP", "Port": 161, "MetricName": "npb_cpu_util" }
          ]
        },
        {
          "Id": "npb-poll",
          "Priority": 2,
          "Metrics": [
            { "Ip": "PLACEHOLDER_NPB_IP", "Port": 161, "MetricName": "npb_mem_util" },
            { "Ip": "PLACEHOLDER_NPB_IP", "Port": 161, "MetricName": "npb_sys_temp" },
            { "Ip": "PLACEHOLDER_NPB_IP", "Port": 161, "MetricName": "npb_port_rx_packets_P1" },
            { "Ip": "PLACEHOLDER_NPB_IP", "Port": 161, "MetricName": "npb_port_tx_packets_P1" }
          ]
        },
        {
          "Id": "obp-poll",
          "Priority": 3,
          "Metrics": [
            { "Ip": "PLACEHOLDER_OBP_IP", "Port": 161, "MetricName": "obp_channel_L1" },
            { "Ip": "PLACEHOLDER_OBP_IP", "Port": 161, "MetricName": "obp_r1_power_L1" },
            { "Ip": "PLACEHOLDER_OBP_IP", "Port": 161, "MetricName": "obp_r2_power_L1" },
            { "Ip": "PLACEHOLDER_OBP_IP", "Port": 161, "MetricName": "obp_channel_L2" }
          ]
        }
      ]
    }
